CREATE TABLE IF NOT EXISTS config (
  name TEXT PRIMARY KEY,
  val TEXT NOT NULL
);
INSERT INTO config VAlUES ( 'mek', '{{ MASTER_ENCRYPTION_KEY }}' );
INSERT INTO config VAlUES ( 'meks', '{{ MASTER_ENCRYPTION_KEY_SALT }}' );
INSERT INTO config VALUES ( 'msk', '{{ MASTER_SIGNING_KEY }}' );
INSERT INTO config VALUES ( 'msks', '{{ MASTER_SIGNING_KEY_SALT }}' );
CREATE TABLE IF NOT EXISTS index (
  uuid TEXT PRIMARY KEY,
  fs_path TEXT PRIMARY KEY,
  ek TEXT NOT NULL,
  sig TEXT NOT NULL
);